#!/bin/bash
docker build --rm -t htschannerl/php:7.4.25 ./php74
docker build --rm -t htschannerl/php:7.4 ./php74
docker build --rm -t htschannerl/php:8.0.12 ./php80
docker build --rm -t htschannerl/php:8.0 ./php80
docker build --rm -t htschannerl/php:latest ./php80

