#!/bin/bash
docker build --rm -t htschannerl/php:7.4.25 ./php74
docker build --rm -t htschannerl/php:7.4 ./php74
docker build --rm -t htschannerl/php:8.0.12 ./php8012
docker build --rm -t htschannerl/php:8.0 ./php8012
docker build --rm -t htschannerl/php:latest ./php8012

docker push htschannerl/php:7.4.25
docker push htschannerl/php:7.4
docker push htschannerl/php:8.0.12
docker push htschannerl/php:8.0
docker push htschannerl/php:latest