version: '3.5'

networks:
  web:
    external: true

services:
 php:
  container_name: php
  image: htschannerl/php:7.4.20
  restart: always
  ports:
    - "8080:80"
  volumes:
#    - ./conf/supervisord/supervisord.conf:/etc/supervisord.conf
    - ./conf/supervisord/supervisord.d:/etc/supervisord.d
    - ./conf/httpd/conf.d:/etc/httpd/conf.d
    - ./conf/php/php.d:/etc/php.d
    - ./conf/php/php-fpm.d:/etc/php-fpm.d
    - ./dados/www:/var/www
#    - ./scripts:/scripts
    - ./logs:/var/log/supervisor
  networks:
    - web