version: '3.5'

networks:
  web:
    external: true

services:
 php:
  container_name: php
  image: local/php:8.0
  restart: always
  ports:
    - "8080:80"
  volumes:
    - ./conf/php/php.d/myphp.ini:/usr/local/etc/php/conf.d/myphp.ini
    - ./dados/www:/var/www
  networks:
    - web