version: '3.5'

networks:
  web:
    external: true

services:
 php:
  container_name: php
  image: local/php:7.4
  restart: always
  ports:
    - "80:80"
  volumes:
    - /mnt/dados/producao/php74/conf/supervisord/supervisord.conf:/etc/supervisord.conf
    - /mnt/dados/producao/php74/conf/supervisord/supervisord.d:/etc/supervisord.d
    - /mnt/dados/producao/php74/conf/httpd/conf.d:/etc/httpd/conf.d
    - /mnt/dados/producao/php74/conf/php/php.d:/etc/php.d
    - /mnt/dados/producao/php74/conf/php/php-fpm.d:/etc/php-fpm.d
    - /mnt/dados/producao/php74/dados/www:/var/www
    - /mnt/dados/producao/php74/scripts:/scripts
    - ./logs:/var/log/supervisor
  networks:
    - web
