version: '3.5'

networks:
  web:
    external: true

services:
 php:
  container_name: php
  image: htschannerl/php:8.3.8
  restart: always
  environment:
    APACHE_LOG_DIR: "/var/log/apache2/"
  ports:
    - "8080:80"
  volumes:
    - ./conf/php/php.d/myphp.ini:/usr/local/etc/php/conf.d/myphp.ini
    - ./dados/www:/var/www
  networks:
    - web