FROM php:8.0.24-apache

RUN apt update \
&& apt install --yes --no-install-recommends \
cron \
wget \
ca-certificates \
jq \
sendmail \
&& rm -rf /var/lib/apt/lists/*

RUN mv /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
install-php-extensions gd mysqli pdo_mysql intl exif zip imagick ldap apcu bz2 opcache