name: Docker Image CI

on:
  push:
    branches: [ "docker" ]

jobs:

  build-x86:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image 8.0
      working-directory: ./Dockerfiles/
      run: docker build . --file Dockerfile --tag htschannerl/php:8.0

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Docker push
      run: docker push --all-tags htschannerl/php

  build-arm64:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu22.04

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image 8.0
      working-directory: ./Dockerfiles/
      run: docker build . --file Dockerfile --tag htschannerl/php:8.0
      with:
          arch: aarch64

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Docker push
      run: docker push --all-tags htschannerl/php
      with:
          arch: aarch64