name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

#    - name: Build the Docker image
#      working-directory: ./php81/
#      run: docker build . --file Dockerfile --tag htschannerl/php:8.1

    - name: Docker Login
      run: docker login -u htschannerl -p $env:DOCKER_PASSWORD
      with:
        verbose: true
      env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker logout
      run: docker logout
      if: ${{ always() && steps.docker_login.outcome != 'skipped' }}