name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image 8.2.20
      working-directory: ./Dockerfiles/
      run: docker build . --file Dockerfile-8.2.20 --tag htschannerl/php:8.2.20

    - name: Build the Docker image 8.3.8
      working-directory: ./Dockerfiles/
      run: docker build . --file Dockerfile-8.3.8 --tag htschannerl/php:latest && docker image tag htschannerl/php:8.3.8 htschannerl/php:8.3

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Docker push
      run: docker push --all-tags htschannerl/php