name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

#    - name: Build the Docker image
#      working-directory: ./php81/
#      run: docker build . --file Dockerfile --tag htschannerl/php:8.1

    - name: Docker Login
      uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker logout
      run: docker logout
      if: ${{ always() && steps.docker_login.outcome != 'skipped' }}