name: Docker Image CI

on:
  push:
    branches: [ "docker" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu22.04

    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Build the Docker image 8.3.8
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}        
          run: docker build . --file Dockerfile-8.3.8 --tag htschannerl/php:latest && docker image tag htschannerl/php:latest htschannerl/php:8.3 && docker image tag htschannerl/php:latest htschannerl/php:8.3.8

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Docker push
        run: docker push --all-tags htschannerl/php